# Provide a Google API key for live scraping or replace this field with
# `demo_fixture_path: path/to/demo_fixture.json` to run the offline demo.
google_api_key: "YOUR_GOOGLE_API_KEY"
request_delay_seconds: 1.5
max_results_per_city: 120
cities:
  - name: "New York"
    region: "NY"
    country: "USA"
  - name: "Seattle"
    region: "WA"
    country: "USA"
  - name: "Vancouver"
    region: "BC"
    country: "Canada"
  - name: "Toronto"
    region: "ON"
    country: "Canada"
  - name: "London"
    region: "England"
    country: "United Kingdom"
  - name: "Paris"
    region: "Île-de-France"
    country: "France"
  - name: "Berlin"
    region: "Berlin"
    country: "Germany"
  - name: "Barcelona"
    region: "Catalonia"
    country: "Spain"
  - name: "Amsterdam"
    region: "North Holland"
    country: "Netherlands"
  - name: "Dublin"
    region: "Leinster"
    country: "Ireland"
